# config/packages/cache.yaml
framework:
    cache:
        pools:
            app.cache:
                adapter: cache.adapter.filesystem
            app.redis_cache:
                adapter: cache.adapter.redis
                provider: 'redis://localhost'
